FROM python:3.12-slim

WORKDIR /QuizAI

COPY tests/ ./tests/

RUN pip install -r tests/tests_requirements.txt

COPY Backend/ ./Backend/

RUN pip install -r Backend/requirments.txt

CMD ["python", "Backend/app.py"]
